CREATE DATABASE ORG;
SHOW DATABASES;
USE ORG;
CREATE TABLE workers(
    WORKER_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    FIRST_NAME CHAR(25),
    LAST_NAME CHAR(25),
    SALARY INT(15),
    JOINING_DATE DATETIME,
    DEPARTMENT CHAR(25)
);
INSERT INTO workers
    (WORKER_ID, FIRST_NAME, LAST_NAME, SALARY, JOINING_DATE, DEPARTMENT) 
VALUES
    (1, 'AYUSH', 'RAJ', 300000, '2023-01-12 00:00:00', 'HR'),
    (2, 'VISHAL', 'YADAV', 300000, '2024-06-02 00:00:00', 'HR'),
    (3, 'SARVESH', 'PANDEY', 46000, '2021-10-13 00:00:00', 'admin'),
    (4, 'SAMEER', 'RAJ', 100000, '2021-02-12 00:00:00', 'admin'),
    (5, 'YASH', 'KUMAR', 210000, '2025-03-08 00:00:00', 'HR');
INSERT INTO workers
    (WORKER_ID, FIRST_NAME, LAST_NAME, SALARY, JOINING_DATE, DEPARTMENT) 
VALUES
    (6, 'HARSHAL', 'KUMAR', NULL, '2023-01-12 00:00:00', 'HR');
SELECT * FROM workers;
SELECT 44+11;
SELECT NOW();
SELECT UCASE('AyusH RAJ');
SELECT FIRST_NAME,SALARY FROM workers;
SELECT * FROM WORKERS WHERE SALARY > 100000;
SELECT * FROM WORKERS WHERE DEPARTMENT='admin';
SELECT * FROM WORKERS WHERE SALARY BETWEEN 50000 AND 200000;
SELECT * FROM WORKERS WHERE DEPARTMENT IN ('HR','ADMIN');
SELECT * FROM WORKERS WHERE DEPARTMENT NOT IN ('HR');
SELECT * FROM WORKERS WHERE SALARY IS NULL;
SELECT * FROM WORKERS ORDER BY SALARY;
SELECT * FROM WORKERS ORDER BY SALARY DESC;
SELECT DISTINCT DEPARTMENT FROM WORKERS;
SELECT * FROM WORKERS WHERE DEPARTMENT NOT IN('ADMIN');
SELECT * FROM WORKERS WHERE FIRST_NAME LIKE '_A%';
SELECT DEPARTMENT,COUNT(DEPARTMENT) FROM WORKERS GROUP BY DEPARTMENT;
SELECT DEPARTMENT,AVG(SALARY) FROM WORKERS GROUP BY DEPARTMENT;
SELECT DEPARTMENT,MIN(SALARY) FROM WORKERS GROUP BY DEPARTMENT;
SELECT DEPARTMENT,MAX(SALARY) FROM WORKERS GROUP BY DEPARTMENT;
SELECT DEPARTMENT,SUM(SALARY) FROM WORKERS GROUP BY DEPARTMENT;
SELECT DEPARTMENT,COUNT(DEPARTMENT) FROM WORKERS GROUP BY DEPARTMENT HAVING COUNT(DEPARTMENT)>2;
